---
on: [push, pull_request]
name: Lints
jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npx eslint . --ext .ts,.tsx
